baseURL: 'https://qhchen.ca'
languageCode: 'en-us'
title: 'Dr. Qinghua Chen'
theme: 'github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-cms/v5'

# Hugo Modules
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5

# Site Parameters
params:
  # Basic Info
  copyright: '© 2025 Qinghua Chen'
  
  # Contact Info
  email: 'me@qhchen.ca'
  phone: '+852 53867520'
  
  # Social Media
  twitter: ''
  github: ''
  linkedin: ''
  orcid: '0000-0001-5212-2163'
  google_scholar: ''
  
  # Features
  highlight: true
  math: true
  diagram: true
  privacy_pack: false
  
  # Site Features
  cms:
    branch: main
    local_backend: false
  
  # SEO
  site_type: Person
  local_business_type: ''
  org_name: 'The Education University of Hong Kong'
  
  # Reading time
  reading_time: true
  section_pager: false
  docs_section_pager: true
  sharing: true
  copyright_license:
    enable: false
  
  # Abstract length
  abstract_length: 135
  
  # Plugins
  plugins_js: []
  
  # Maps
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Menu Configuration
menu:
  main:
    - name: Home
      url: '#about'
      weight: 10
    - name: Research
      url: '#research'
      weight: 20
    - name: Publications
      url: '#publications'
      weight: 30
    - name: Teaching
      url: '#teaching'
      weight: 40
    - name: Projects
      url: '#projects'
      weight: 50
    - name: Contact
      url: '#contact'
      weight: 60
    - name: CV
      url: '/uploads/cv.pdf'
      weight: 70

# Taxonomies
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors

# Security
security:
  enableInlineShortcodes: false
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_

# Markup
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

# Privacy
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: false
    anonymizeIP: true
  instagram:
    disable: true
  twitter:
    disable: false
    enableDNT: true
  vimeo:
    disable: true
  youtube:
    disable: false
    privacyEnhanced: true