baseURL = "https://qhchen.ca"
languageCode = "en-us"
title = "Dr. Qinghua Chen - Academic Portfolio"

[params]
  author = "Qinghua Chen"
  email = "me@qhchen.ca"
  description = "Postdoctoral Fellow specializing in language education and poststructuralist theory"
  orcid = "0000-0001-5212-2163"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 3

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 4

[[menu.main]]
  name = "CV"
  url = "/uploads/cv.pdf"
  weight = 5